### ISSUE TITLE
Where's all the documentation? How do you use {% include %}

### ISSUE THREAD

**Issue by mudlabs** [electron/electronjs.org#5200]
I'm trying to use include to get data in a yaml file that's related to a list item in my template. But I just get `Liquid.ArgumentError: Illegal template name my-item-file.yaml`

**For example**

```html
<!-- component.html -->
<ul>
  {% for item in items %}
  {% include {{item.slug}}.yaml %}
  <li>
    <h1>{{ include.title }}</h1>
    <img src="{{ include.thumbnail }}" alt="{{ include.description }}" />
  </li>
  {% endfor %}
</ul>
```

```yaml
# data.yaml
items:
  - slug: file-1
  - slug: file-2
```

```yaml
# file-1.yaml
tile: File 1 Title
thumbnail: http://thumbnail-image-path
description: Thumbnail description
```

```js
// engine.js
const engine = new liquid.Engine();
engine.registerFileSystem(new liquid.LocalFileSystem("./", "yaml"))

async function liquify(component, data) {
  const template = await engine.parse(component);
  const result = await template.render(data);
  return result;
}
```
